
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-staff
owner: ucsb-cs156-s26
repo_name: team01-s26-staff
pull_requests: [{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-Articles-put","number":95,"title":"Ac articles put","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/95"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-Articles-get-by-id","number":94,"title":"Ac articles get by id","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/94"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-Articles-create-controller","number":93,"title":"Ac articles create controller","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/93"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-correctRepository","number":92,"title":"Supressing Automatic Endpoints on DiningCommonsMenuItemRepository","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/92"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addDelete","number":91,"title":"Adding the DELETE endpoint for DiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/91"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addPut","number":90,"title":"Adding the PUT endpoint for DiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/90"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-singularGet","number":89,"title":"Adding the GET/show endpoint for DiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/89"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-postAndGetAll","number":88,"title":"Creating the POST and ALL endpoints for Dining Commons Menu Items","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/88"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-Articles-create-db","number":87,"title":"ac - create database table for Articles","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/87"}]
