
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-staff
owner: ucsb-cs156-s26
repo_name: team01-s26-staff
pull_requests: [{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-rrcontroller","number":99,"title":"dk - rr post and get","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/99"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-get-post","number":98,"title":"Dp - Added help request controller and GET & POST endpoints","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/98"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-create-db","number":97,"title":"dp - Added entity, repository, db migration files for the database table. ","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/97"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-Articles-delete","number":96,"title":"Ac articles delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/96"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-Articles-put","number":95,"title":"Ac articles put","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/95"}]
