
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-staff
owner: ucsb-cs156-s26
repo_name: team01-s26-staff
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-put-endpoint","number":108,"title":"ka - PUT endpoint controller + tests","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/108"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-delete-endpoint","number":107,"title":"ka - DELETE endpoint controller + tests","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/107"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-get-by-id","number":106,"title":"ka - GET by id endpoint controller and tests","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/106"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-getall-post-endpoints","number":105,"title":"ka -adds GET all and POST endpoint controllers and tests","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/105"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":"Wendy Song"},"headRefName":"ws-ucsborganization-get","number":104,"title":"added GET by id for ucsborganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/104"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":"Wendy Song"},"headRefName":"ws-ucsborganizationcontroller","number":103,"title":"added GET and POST for ucsborganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/103"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-db-setup","number":102,"title":"ka - MenuItemReveiw set up","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/102"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":"Wendy Song"},"headRefName":"ws-ucsborganization-branch","number":101,"title":"ucsborganization database","url":"https://github.com/ucsb-cs156-s26/team01-s26-staff/pull/101"}]
